### ISSUE TITLE
MoCapNatNetClient printing to terminal

### ISSUE THREAD

**Issue by mstoelzle** [tud-cor-sr/ros2-mocap_optitrack#6]
I noticed that the `MoCapNatNetClient.cpp` is printing quite a lot to the terminal which is certainly great for debugging. Do you think it would make sense to add a setting to the classe, to activate / deactivate the logging? Basically adding a debug mode, which only prints if its activated

https://github.com/tud-cor-sr/ros2-mocap_optitrack/blob/master/mocap_optitrack_client/src/MoCapNatNetClient.cpp#L224

**Comment by piepustina** [comment]
Moved most of the messages as DEBUG of ROS2
